### ISSUE TITLE
Celltypes for deconvoluion

### ISSUE THREAD

**Issue by wangzlgithub** [saezlab/visium_heart#11]
Hello! Thanks for sharing this excellent work!
I see that in your article there is not only a MISTy analysis of the main clusters, but also a MISTy analysis of certain subclusters.
Did you analyze the results of cell2location with MISTy? If so, the latter analysis you did is how to achieve? Only input these certain subcluters, or you input all celltypes with subclusters?

**Comment by roramirezf** [comment]
Hi!

The analysis of the subclusters was done with a modified MISTy pipeline that goes as follows:

1) We defined a predictive model of the cell-state scores of a cell-type of interest using the abundance of other major cell-types (eg. CM states as in Fig. 4k-l). This was only done for certain cell-states (or subclusters, as you call them :))

2) First, for each slide we generated regions of interest (ROIs) for our cell-states, which meant that we first checked from the cell2location estimates which spots contained at least 10% of the major cell-type.

3) For those ROIs we fitted the model, however the cell2location abundances of all the spots within each slide were used as predictors.

Note that the cell-states scores were not calculated with cell2location but rather with the weighted mean of the marker expression.
