### ISSUE TITLE
Would you mind releasing scripts related to match ATAC and RNA?

### ISSUE THREAD

**Issue by frucelee** [saezlab/visium_heart#13]
Hi,

Thank you so much for the very nice paper and shared the code for us to learn. We are interested in learning how to integrate the data using the method you described. As mentioned in the section "12_matching_ATAC_RNA.ipynb", two scripts were described as fllows; source("../../utils/stimATAC_analyses_code/R/utils.R")
source("../../utils/stimATAC_analyses_code/R/optMatching_functions.R")

However, we can't found the where is utils.R and optMatching_functions.R. Is it possible for you to share us with them. Thanks a lot.

**Comment by lzj1769** [comment]
Hi @frucelee ,

Sorry for the late reply.

We have now complied the codes as a R package called scMEGA to infer GRN based on the matched ATAC and RNA, you can find the tutorial here:
https://costalab.github.io/scMEGA/articles/myofibroblast-GRN.html

Specifically, you can run the function [CoembedData](https://costalab.github.io/scMEGA/reference/CoembedData.html) and [PairCells](https://costalab.github.io/scMEGA/reference/PairCells.html) to integrate and match the two modalities.

Let me know if you have any issues when running the package.

Best,
Zhijian

**Comment by frucelee** [comment]
Super. Thanks a lot.
