### ISSUE TITLE
Where is get_cell_states.R file?

### ISSUE THREAD

**Issue by Fanzwstatis** [saezlab/visium_heart#14]
Hi, I really appreciate your contribution. According to your code, get_cell_states.R file might be essential for this analysis. It is hard to regenerated, could you kindly tell me how to download it?

**Comment by roramirezf** [comment]
Hi,

Thanks for noticing this. The jobs that require the get_cell_states.R file are deprecated and were part of a previous analysis that was not related to the generation of the cell-states. For cell-state definition please consult
https://github.com/saezlab/visium_heart/tree/db4d51ff033a6f25b24c99a275ea415128741f63/sub-clustering

**Comment by roramirezf** [comment]
Fixed on commit [5b30c7e](https://github.com/saezlab/visium_heart/commit/5b30c7e497e06688a8448afd8d069d2fa70ebcd2)
