### ISSUE TITLE
batch lables missing for snRNA-seq integration

### ISSUE THREAD

**Issue by lengfei5** [saezlab/visium_heart#18]
Hi there, 

Highly appreciate the precious human heart data and cool analysis.

We are using the human heart data by selecting mainly the control and early injury samples to compare our axolotl heart data. 
So we want to rerun the data integration using Harmony or alternatives. 

In the "snRNA-seq data processing" of your paper, it was described how to perform the integration step:
"To select the collection of shared variable genes between samples, first we estimated the top 3,000 most variable genes per sample and then selected the top 3,000 most-recurrent genes from them across all samples. PCA correction was performed with harmony[62](https://www.nature.com/articles/s41586-022-05060-x#ref-CR62) (v1.0) using as covariates the **patient, sample, and batch labels**."

To find the batch labels information, I have looked through the supplementary tables and also Zenodo link: https://zenodo.org/record/7098004#.Y0P_LC0RoeY and still did not manage.

Could you please show me where to find it ? many thanks.

Many thanks.

**Comment by roramirezf** [comment]
Hi Leng, sorry for the late reply. Batches are represented by the prefix on the sample id. ACH or 10X. I will provide a table with that information as soon as I can, but you can already obtain it from the ids if needed.

**Comment by lengfei5** [comment]
many thanks for your answer which is extremely helpful. 

Best,
