### ISSUE TITLE
Would you mind releasing scripts related to cell cycle score?

### ISSUE THREAD

**Issue by wangyiqing50** [saezlab/visium_heart#6]
Hi, I am reading the paper and find it a very informative manuscript. 
I was wondering if I can check the code on how exactly the cell cycle score was calculated.

**Comment by roramirezf** [comment]
Sorry for the delay,

I have added the missing script here: https://github.com/saezlab/visium_heart/blob/master/st_snRNAseq/02_snuc_integration_harmony/estimate_cellcycle.R

It is based on Seurat's annotation.

Cheers
