### ISSUE TITLE
About the file annotation.rds in get_states_dea.R

### ISSUE THREAD

**Issue by jianlion** [saezlab/visium_heart#8]
Hi, I really appreciate your contribution. Can you please elaborate how the file _annotation.rds_ in _get_states_dea.R_ was generated?

**Comment by roramirezf** [comment]
Thanks for the comment,

These files come from the raw annotation of cell states gotten after the integration of scell RNA and ATAC data, their names changed during the manuscript writing so I didn't share them as they were. Nevertheless, we acknowledge the necessity of these annotations.

We discussed with @lzj1769 , who made the annotations, and we will provide them as soon as possible in an extension of the Zenodo repos. 

Sorry for the inconvenience, but I will be back to you as soon as I have them.

**Comment by Kai6662** [comment]
Hi,

Thank you for sharing these scripts with us! 
I am trying to use your data as well. I downloaded "All-snRNA-Spatial multi-omic map of human myocardial infarction" Rdata from Cellxgene. I can find cell types and genes and a lot of useful information from the Seurat data. Thank you for that. But unfortunately, I could not get the cell clusters. From UMAP, I can only see the "local" group.  Do you know how can I get the cell type identity? I checked all the codes here. It is like I need to rerun all the codes using the raw data in the beginning. If you know how can I use the specific parts of codes on the Seurat  RDS file to get the cell type identity and clusters? 

Best regards,
Kai

**Comment by roramirezf** [comment]
The cell-states can be found in the following link: https://zenodo.org/record/7098004#.Y0P_SOxBweZ

Cheers
