### ISSUE TITLE
 Cell type clustering 

### ISSUE THREAD

**Issue by Kai6662** [saezlab/visium_heart#9]
Hi,

Thank you for sharing these scripts with us!
I am trying to use your data as well. I downloaded "All-snRNA-Spatial multi-omic map of human myocardial infarction" Rdata from Cellxgene(https://cellxgene.cziscience.com/collections/8191c283-0816-424b-9b61-c3e1d6258a77). I can find cell types and genes and a lot of useful information from the Seurat data. Thank you for that. But unfortunately, I could not get the cell clusters. From UMAP, I can only see the "local" group. Do you know how can I get the cell type identity or how can I repeat cell type clustering? I checked all the codes here. It is like I need to rerun all the codes using the raw data in the beginning. If you know how can I use the specific parts of codes on the Seurat RDS file to get the cell type identity and clusters?

Best regards,
Kai

**Comment by roramirezf** [comment]
Hi Kai,

Here you can find the objects containing the cell-state information: https://zenodo.org/record/7098004#.Y0P_SOxBweZ

The code to obtain those will be uploaded in the next days :)

Cheers

**Comment by roramirezf** [comment]
The code has been added in main branch
